language: cpp

matrix:
  include:
    # macOS Sierra
    - os: osx
      osx_image: xcode9.2
    # macOS High Sierra
    - os: osx
      osx_image: xcode10.1
    # macOS Mojave
    - os: osx
      osx_image: xcode10.2

script:
  - if [[ "$TRAVIS_OSX_IMAGE" == "xcode9.2" ]]; then
      clang++ -std=c++1z -I./include examples/basic.cpp -o basic && ./basic;
    else
      clang++ -std=c++17 -I./include examples/basic.cpp -o basic && ./basic;
    fi

notifications:
  email: false

